import link from "next/link"

import './globals.css'

export const metadata = {
  title: 'Núnka Magazine',
  description: 'Generated by create next app',
}

export default function ({  }) {
  return (
    <html lang="es">
  <head>
    
    <title>Núnka Magazine</title>
    
  </head>
  <body>
    <header>
      
      <nav>
        <ul>
        <div class="space-x-20 text-center absolute inset-x-0 top-[35px]  left-[550px] text-ls">
          <li><a href="page.js">Inicio</a></li>
          <li><a href="/..pages/Myabout">Nosotros</a></li>
          <li><a href="#">Contacto</a></li>
          </div>
        </ul>
      </nav>
    </header>
    
    <main>
     
    </main>
    
    <footer>
      
      <p>Todos los derechos reservados &copy; 2023</p>
    </footer>

  </body>
</html>
    
    
    
  )
}
