import link from "next/link"


const links=[{
  label:"Homepage", 
  route:"/"
}, {
label:"about",
route:"/aboutPage"
}

] 
import './globals.css'

export const metadata = {
  title: 'Núnka Magazine',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <header>
      <nav>
        <ul>
        {links.map(({label,route}) => (
          <li key={route}>
            <link href={route}>
            {label}
            </link>
          </li>
        ))}

        </ul>
      </nav>
    </header>
      
      <body>{children}</body>
    </html>
  )
}
